language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install .
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1-bin-hadoop2.6.tgz
  - tar -xzf spark-1.5.1-bin-hadoop2.6.tgz

script:
  - export SPARK_HOME=`pwd`/spark-1.5.1-bin-hadoop2.6
  - export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH
  - export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.8.2.1-src.zip:$PYTHONPATH
  - py.test